apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.componentname" (list . "admintools") }}
  {{- include "temporal.namespace" $ | indent 2 }}
  labels:
    {{- include "temporal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: admintools
spec:
  type: ClusterIP 
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh

  selector:
    {{- include "temporal.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: admintools

