{{- if $.Values.server.enabled }}
{{- range $store := (list "default" "visibility") }}
{{- $storeConfig := index $.Values.server.config.persistence $store }}
{{- $driverConfig := index $storeConfig (include "temporal.persistence.driver" (list $ $store)) }}
{{- $secretName := include "temporal.componentname" (list $ (printf "%s-store" $store)) }}
{{- if and (not $driverConfig.existingSecret) (eq (include "temporal.persistence.secretName" (list $ $store)) $secretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  {{- include "temporal.namespace" $ | indent 2 }}
  labels:
    {{- include "temporal.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if eq (include "temporal.persistence.driver" (list $ $store)) "cassandra" }}
  password: {{ $storeConfig.cassandra.password | b64enc | quote }}
  {{- else if eq (include "temporal.persistence.driver" (list $ $store)) "sql" }}
  password: {{ include "temporal.persistence.sql.password" (list $ $store) | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
