{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "temporal.componentname" (list . "web") }}
  {{- include "temporal.namespace" $ | indent 2 }}
  labels:
    {{- include "temporal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "temporal.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "temporal.labels" $ | nindent 8 }}
        app.kubernetes.io/component: web
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ include "temporal.serviceAccount" . }}
      volumes:
        - name: {{ .Chart.Name }}-web-config
          configMap:
            name: {{ include "temporal.componentname" (list . "web") }}-config
      containers:
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            - name: TEMPORAL_GRPC_ENDPOINT
              value: "{{ include "temporal.fullname" . }}-frontend.{{ .Release.Namespace }}.svc:{{ .Values.server.frontend.service.port }}"
            {{- if .Values.web.permitWriteAPI }}
            - name: TEMPORAL_PERMIT_WRITE_API
              value: "true"
            {{- end }}
          volumeMounts:
            - name: {{ .Chart.Name }}-web-config
              mountPath: /usr/app/server/config.yml
              subPath: config.yml
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext:
            {{- toYaml $.Values.web.podSecurityContext | nindent 12 }}
      securityContext:
        {{- toYaml $.Values.web.securityContext | nindent 8 }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
