{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.componentname" (list . "web") }}
  {{- include "temporal.namespace" $ | indent 2 }}
  labels:
    {{- include "temporal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: web
{{- with .Values.web.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- with .Values.web.service.loadBalancerIP }}
  loadBalancerIP: {{.}}
    {{- end }}
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if hasKey .Values.web.service "nodePort" }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  selector:
    {{- include "temporal.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: web
  {{- end }}
