name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - jw-more-configuration

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add helm depdenencies
        run: |
          helm repo add cassandra https://charts.helm.sh/incubator
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add elasticsearch https://helm.elastic.co
          helm repo add grafana https://grafana.github.io/helm-charts

      - name: Move Chart files to charts/temporal/
        run: |
          mkdir -p charts/temporal
          git ls-tree --name-only HEAD | \
            egrep -v '(.github|.gitignore)' | \
            xargs -I{} cp -R {} charts/temporal

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
